### ISSUE TITLE
Unterminated coveralls ignores

### ISSUE THREAD

**Issue by tonyvanriet** [elixir-git/xgit#185]
- [ ] Add label: "TO DO"
- [ ] Add label: "good first issue" or "help wanted" if appropriate
- [ ] Add link to this issue in a comment near the `TO DO` comment

**Describe What Is Incomplete**
I noticed that you've used the coveralls line-level ignore in a few places, but it's being terminated with `# coveralls-ignore-end` instead of `# coveralls-ignore-stop`.
We noticed ourselves doing this exact same thing accidentally, and as a result, coveralls was ignoring the rest of the file completely rather than turning off the ignore at the desired point.
https://github.com/parroty/excoveralls/issues/197

I intended to search our codebase to make sure we got them all. I searched all of github instead, and happened upon the two examples in xgit. Thought I'd let you know. :)
https://github.com/elixir-git/xgit/search?q=coveralls-ignore-end&unscoped_q=coveralls-ignore-end

**Definition of Done**
All uses of `# coveralls-ignore-start` have an associated `# coveralls-ignore-stop`.

**Comment by scouten** [comment]
Nice catch. Thank you!
